### ISSUE TITLE
Error in eval(expr, envir, enclos) : object 'probe' not found

### ISSUE THREAD

**Issue by PFRoux** [borishejblum/TcGSA#9] opened 2015-08-13 13:38 UTC
Dear Boris,

I would like to run TcGSA.LR on a timecourse data set (6 time point, each time point in duplicates).

Using the sample dataset you provide with the package, I am having the following issue :

<img width="563" alt="capture d ecran 2015-08-13 a 15 35 56" src="https://cloud.githubusercontent.com/assets/12641881/9250987/0a3e798a-41d1-11e5-96ca-be834dc1ccf8.png">

Could you help me please to figure out what's going on ?

Thx !

Pierre-François

> sessionInfo()
> R version 3.2.1 (2015-06-18)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.10.4 (Yosemite)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
 [1] grid      tcltk     stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] multtest_2.24.0                      GSA_1.03                             TcGSA_0.9.8  
 [4] lme4_1.1-8                           Matrix_1.2-2                         maSigPro_1.40.0  
 [7] MASS_7.3-43                          ggplot2_1.0.1                        reshape_0.8.5  
[10] ChIPpeakAnno_3.2.2                   VennDiagram_1.6.9                    VariantAnnotation_1.14.10  
[13] Rsamtools_1.20.4                     GenomicFeatures_1.20.1               GenomicRanges_1.20.5  
[16] topGO_2.20.0                         SparseM_1.6                          GO.db_3.1.2  
[19] graph_1.46.0                         Mfuzz_2.28.0                         DynDoc_1.46.0  
[22] widgetTools_1.46.0                   e1071_1.6-7                          edge_2.0.0  
[25] biomaRt_2.24.0                       hugene20sttranscriptcluster.db_8.3.1 org.Hs.eg.db_3.1.2  
[28] FactoMineR_1.31.3                    pd.hugene.2.0.st_3.14.1              RSQLite_1.0.0  
[31] DBI_0.3.1                            annotate_1.46.1                      XML_3.98-1.3  
[34] AnnotationDbi_1.30.1                 GenomeInfoDb_1.4.1                   oligo_1.32.0  
[37] Biostrings_2.36.3                    XVector_0.8.0                        IRanges_2.2.7  
[40] S4Vectors_0.6.3                      Biobase_2.28.0                       oligoClasses_1.30.0  
[43] BiocGenerics_0.14.0                  BiocInstaller_1.18.4                

loaded via a namespace (and not attached):
 [1] nlme_3.1-121            bitops_1.0-6            pbkrtest_0.4-2          tools_3.2.1  
 [5] affyio_1.36.0           KernSmooth_2.23-15      mgcv_1.8-7              colorspace_1.2-6  
 [9] nnet_7.3-10             bit_1.1-12              preprocessCore_1.30.0   quantreg_5.11  
[13] flashClust_1.01-2       labeling_0.3            rtracklayer_1.28.7      caTools_1.17.1  
[17] scales_0.2.5            genefilter_1.50.0       RBGL_1.44.0             stringr_1.0.0  
[21] digest_0.6.8            minqa_1.2.4             limma_3.24.15           BSgenome_1.36.3  
[25] gtools_3.5.0            BiocParallel_1.2.20     car_2.0-26              RCurl_1.95-4.7  
[29] magrittr_1.5            leaps_2.9               futile.logger_1.4.1     Rcpp_0.12.0  
[33] munsell_0.4.2           proto_0.3-10            scatterplot3d_0.3-36    stringi_0.5-5  
[37] zlibbioc_1.14.0         gplots_2.17.0           plyr_1.8.3              qvalue_2.0.0  
[41] affxparser_1.40.0       gdata_2.17.0            lattice_0.20-33         splines_3.2.1  
[45] tkWidgets_1.46.0        corpcor_1.6.8           reshape2_1.4.1          codetools_0.2-14  
[49] futile.options_1.0.0    lambda.r_1.1.7          snm_1.16.0              nloptr_1.0.4  
[53] foreach_1.4.2           gtable_0.1.2            xtable_1.7-4            ff_2.2-13  
[57] class_7.3-13            survival_2.38-3         iterators_1.0.7         GenomicAlignments_1.4.1
[61] cluster_2.0.3           sva_3.14.0

**Comment by borishejblum** [comment] 2015-08-13 15:42
Dear Pierre-François,

First thank you very much for your interest in TcGSA (you are the first TcGSA user to ever write to me, this is very exciting)!

Unfortunately, I am not able to replicate your error, which makes it hard for me to help…
I see that you are using R latest version, and the CRAN 0.9.8 version of TcGSA package (which is the stable version), so that is good.

Please make sure to execute the following, and let me know what is the output :

install.package(“TcGSA”)
library(TcGSA)
rm(list=ls())
data(data_simu_TcGSA)
tcgsa_sim_2grp <- TcGSA.LR(expr=expr_2grp, gmt=gmt_sim, design=design,
                          subject_name="Patient_ID", time_name="TimePoint",
                          time_func="linear", crossedRandom=FALSE,
                          group_name="group.var")
tcgsa_sim_2grp

Let me know how this goes, I am happy to help further resolving this issue or any other you might have using the package.

Thanks,
Boris

**Comment by PFRoux** [comment] 2015-08-13 17:45
Dear Boris,

Thanks a lot for being so prompt to answer !

I must confess I am excited too to test your tool. I’ve been looking for a while for something allowing to run GSEA-like test on timecourse data.
And it is definitely not a common thing !

I am sorry for my previous report : I managed to solve this by restarting everything in a fresh R session.
Now TcGSA works fine on the toy dataset.

May I ask you help to solve my next problem ?
I’ve dowloaded gene set on the Broad Institute website and imported them in R using GSA.read.gmt().



As expected, they met all the criteria for a bona fide gene set object ready for a GSEA analysis in R.




Nevertheless, TcGSA complain about the size of all gene sets (too many or too few genes) contained in the object created with GSA.read.gmt().

Best !

Pierre-François

**Comment by borishejblum** [comment] 2015-08-13 18:27
Hi Pierre-François,

I suppose the behavior you are describing is due to the ```minGSsize``` and ```maxGSsize``` arguments. If a gene set supplied has fewer genes than ```minGSsize``` or more genes than ```maxGSsize```, than it is not analyzed, a warning is issued and the results for this gene set should be ```NA```. As ```minGSsize=10``` and ```maxGSsize=500``` by default, I certainly expect some gene sets from the Broad Institute website to be outside of those bounds, but not all of them. 
Can you confirm that this is indeed the problem you are facing ?

If so, you can change the value of ```minGSsize``` and ```maxGSsize``` to be able to analyze all the gene sets you are interested in.

Best, 
Boris

**Comment by PFRoux** [comment] 2015-08-14 07:39
Hi Boris, 

Of course I was aware of the parameters maxGSize & minGSize, and they were properly set when I had this issue.

I finally figured out what happened : It seems that TcGSA is not able to deal with gene names.

Indeed, I was first working with a GSA object containing gene name lists in the slot GSA$genesets (ans of course, with an expression data.frame with gene names as row names).
I finally converted the names contained in GSA$genesets in probe number (I am working with a human HuGene 2.0 ST array, for which the probe name is numeric only) and get back to the original expression data.set with probe names as row names. And it finally worked …

Best,

Pierre-François


For sure, I was aware of the parameters

**Comment by borishejblum** [comment] 2015-08-14 19:26
Hi Pierre-François,

TcGSA is actually able to deal with gene names (see ```GMTs_PLOScb.RData``` file from the supplementary material of the article, which is using names). 
Could you provide a reproducible example so that I can get a better sense of the error you are facing ?

Thanks,
Boris

**Closed** 2017-05-02 14:30 UTC
Labels: question
