### ISSUE TITLE
Impossible to create plot with plot1GS + warnings when computing the Likelihood Ratios 

### ISSUE THREAD

**Issue by PFRoux** [borishejblum/TcGSA#10] opened 2015-08-14 13:39 UTC
Hi again Boris,

I am sorry to be back ...
But since there is no clear tutorial and manual for the tool, I am facing issues at almost each step. 

To have a look at something more helpful than the R help pages, I am working on the R code you have submitted as supplementary material with your article.

And even with your code I didn't manage to run an analysis without getting error.
I even reinstalled R to be sure the problem has nothing to do with my installation. But I am still having the same issues.

1) Do you remember the first error I get with TcGSA.LR ?
To avoid it, I realized I need to load TcGSA library immediately before launching any TcGSA command. In the case I load another library in between, I get this error.

<img width="563" alt="0a3e798a-41d1-11e5-96ca-be834dc1ccf8" src="https://cloud.githubusercontent.com/assets/12641881/9274601/84c15ea4-4297-11e5-8441-db76236a125d.png">

It seems that TcGSA is not stable depending on other libraries loaded.

2) Working on the script you provide with the article, I am not able to produce the first plot.
I've sanity-checked the data dowloaded on GEO, and everything looks fin.

<img width="670" alt="capture d ecran 2015-08-14 a 15 21 45" src="https://cloud.githubusercontent.com/assets/12641881/9274705/363af956-4298-11e5-882d-03a71009a8f4.png">

3) In the cases I managed to run TcGSA.LR on my own data, I get many warning messages that were not much clear to me. Could you provide some information ?

```
          - Aggregation function missing: defaulting to length :
```

<img width="359" alt="capture d ecran 2015-08-14 a 15 26 31" src="https://cloud.githubusercontent.com/assets/12641881/9274806/f3fa9fd2-4298-11e5-89a1-269c39f58f18.png">

```
         - Fail to converge (quite explicite ... but how to handle this ?)
```

<img width="650" alt="capture d ecran 2015-08-14 a 15 28 49" src="https://cloud.githubusercontent.com/assets/12641881/9274833/3a21f186-4299-11e5-9708-d0b29c538df6.png">

```
         - Fail to converge : degenerate Hessian with 1 negative eigenvalue
```

<img width="530" alt="capture d ecran 2015-08-14 a 15 30 01" src="https://cloud.githubusercontent.com/assets/12641881/9274865/769bd44c-4299-11e5-91ef-2dc3cf532a85.png">

```
         - Maximum number of function evaluations exceeded 
```

<img width="653" alt="capture d ecran 2015-08-14 a 15 31 11" src="https://cloud.githubusercontent.com/assets/12641881/9274879/965e6a6a-4299-11e5-961e-34857f028337.png">

At the end of the analysis, I was quite surprised since 90% of the gene list I used were significant at FDR 5%.

Just a reminder.
Basically, I have two "patients" (they are actually two batches of cells treated with the same drug) and one array at Time 1,2 ... 6 for both. I am interested in gene sets which expression is variable though time.

Here is the design matrix I am using.

<img width="244" alt="capture d ecran 2015-08-14 a 15 34 29" src="https://cloud.githubusercontent.com/assets/12641881/9274933/0604d4bc-429a-11e5-991f-3d57e892d283.png">

Thanks a lot for your time.

Pierre-François

> sessionInfo()
> R version 3.2.1 (2015-06-18)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.10.4 (Yosemite)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] biomaRt_2.24.0      oligoClasses_1.30.0 RSQLite_1.0.0       DBI_0.3.1           TcGSA_0.9.8  
[6] lme4_1.1-8          Matrix_1.2-2       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0          BiocInstaller_1.18.4 XVector_0.8.0        GenomeInfoDb_1.4.1   nloptr_1.0.4  
 [6] plyr_1.8.3           iterators_1.0.7      bitops_1.0-6         tools_3.2.1          zlibbioc_1.14.0  
[11] bit_1.1-12           digest_0.6.8         nlme_3.1-121         gtable_0.1.2         lattice_0.20-33  
[16] ff_2.2-13            foreach_1.4.2        parallel_3.2.1       proto_0.3-10         stringr_1.0.0  
[21] cluster_2.0.3        Biostrings_2.36.3    S4Vectors_0.6.3      IRanges_2.2.7        gtools_3.5.0  
[26] caTools_1.17.1       stats4_3.2.1         multtest_2.24.0      grid_3.2.1           Biobase_2.28.0  
[31] AnnotationDbi_1.30.1 XML_3.98-1.3         survival_2.38-3      gdata_2.17.0         minqa_1.2.4  
[36] GSA_1.03             ggplot2_1.0.1        reshape2_1.4.1       magrittr_1.5         codetools_0.2-14  
[41] GenomicRanges_1.20.5 scales_0.2.5         gplots_2.17.0        MASS_7.3-43          splines_3.2.1  
[46] BiocGenerics_0.14.0  colorspace_1.2-6     KernSmooth_2.23-15   stringi_0.5-5        RCurl_1.95-4.7  
[51] munsell_0.4.2        affyio_1.36.0

**Comment by borishejblum** [comment] 2015-08-14 15:06
Hi Pierre-François

Thanks for the feedback and your efforts to make this work. 
Writing a Vignette manual is on my todo list... ! 

Concerning your questions:

1) Could you tell me which libraries causes this error when loaded prior to TcGSA ? Then I can reproduce the error (hopefully) and correct it. Thanks

2) I am unable to reproduce this error using the supplementary material of the article (I just re-downloaded it and reinstall TcGSA from CRAN). I was able to get the plot right away (there are a few glitches with ggplot2 imports, that I will be fixed on the github version of the package in a commit later today — but as long as you load ggplot2 with ```library(ggplot2)``` before calling ```plot1GS``` it should work).

3) Those warnings likely come from lme4, the package TcGSA relies upon to fit linear mixed effect models. The warnings you get are probably because you have so few replicates (only 2) to estimate the random effects, so lme4 cannot achieve convergence when fitting the mixed models. The results you get are therefore probably untrustworthy. I would advise against using TcGSA with so few replicates, because mixed models normality assumption on the random effects are then very questionnable. You could look into CAMERA or globalANCOVA that could be better suited to analyze your data.

Thanks a lot for you feedback, this helps me improve the TcGSA package !
Boris

**Closed** 2017-05-02 13:00 UTC
Labels: help wanted
