### ISSUE TITLE
Question about interpreting GSA plots

### ISSUE THREAD

**Issue by friedue** [borishejblum/TcGSA#18] opened 2019-04-24 16:00 UTC
Hi,

my question is not strictly about a technical matter, so if you prefer that I post it elsewhere (e.g. bioconductor forum, biostars), let me know and we can move there.

I'm just having a few difficulties applying and understanding the TcGSA methods to a data set of mine and wanted to make sure that I'm using it correctly.

I have a data set with 2 groups ("FM" and "control"), 5 time points and 3-6 replicates per day and group. I am interested in the gene sets that show a change in the FM group compared to the control group.

This is my code for running TcGSA:

```
> str(si.df)
'data.frame':	44 obs. of  6 variables:
  $ day      : num  1 1 1 3 3 3 5 5 5 7 ...
$ condition: Ord.factor w/ 3 levels "EV"<"FM"<"ZB": 2 2 2 2 2 2 2 2 2 2 ...
$ replicate: Factor w/ 3 levels "r1","r2","r3": 1 2 3 1 2 3 1 2 3 1 ...
$ sample   : chr  "FM_d1_r1" "FM_d1_r2" "FM_d1_r3" "FM_d3_r1" ...
$ subject  : Factor w/ 9 levels "FM_r1","FM_r2",..: 1 2 3 1 2 3 1 2 3 1 ...
$ group    : Factor w/ 2 levels "control","FM": 2 2 2 2 2 2 2 2 2 2 ...

> head(si.df)
               day condition replicate   sample subject   group
FM_d1_r1   1        FM        r1 FM_d1_r1          FM_r1      FM
FM_d1_r2   1        FM        r2 FM_d1_r2         FM_r2      FM
FM_d1_r3   1        FM        r3 FM_d1_r3         FM_r3      FM
FM_d3_r1   3        FM        r1 FM_d3_r1         FM_r1      FM
FM_d3_r2   3        FM        r2 FM_d3_r2       FM_r2      FM
FM_d3_r3   3        FM        r3 FM_d3_r3        FM_r3      FM

> head(norm.df)[, 1:13]
          FM_d1_r1 FM_d1_r2 FM_d1_r3 FM_d3_r1 FM_d3_r2 FM_d3_r3 FM_d5_r1 FM_d5_r2 FM_d5_r3 FM_d7_r1 FM_d7_r2 FM_d7_r3 FM_d9_r1
1         6.494755 6.344666 6.626895 6.302365 6.556349 6.279674 6.457430 6.431081 6.373545 6.439920 6.496037 6.193764 6.567713
10        3.903561 4.046803 3.922575 3.651197 3.985549 3.816258 3.766103 3.939777 3.912864 3.856120 4.107793 3.699178 3.733018
100       6.259442 6.433463 6.257839 6.381139 6.333556 6.242901 6.151751 6.245049 6.088381 6.203096 6.127831 6.230802 6.222703
1000      6.579788 6.609205 6.481560 6.945100 6.900424 7.018252 7.576558 7.473344 7.651034 7.816586 7.608644 7.811477 7.859887
10000     6.917100 7.067305 6.757886 6.743027 6.645854 6.987424 7.175362 7.256524 7.413144 7.510972 7.354749 7.519900 7.256954
100008586 2.841318 3.163644 2.996410 2.789338 2.977852 2.753353 3.087226 2.841785 2.806914 2.769058 2.843817 2.788809 2.862810

> gmt_hallmark <- GSA::GSA.read.gmt("h.all.v6.2.entrez.gmt")

> tcgsa_result <- TcGSA::TcGSA.LR(expr = norm.df, 
                                gmt = gmt_hallmark,
                                design = si.df[colnames(norm.df),], 
                                subject_name = "subject", 
                                time_name = "day", 
                                group_name = "group")
> summary(tcgsa_result)
		A TcGSA object
Form of the time trend:
	linear
Number of treatment groups:
	2
Number of gene sets tested for significant time trend:
	50

Number of significant gene sets at a 5% threshold (BY procedure):
	35 out of 50 gene sets
```

My question is mostly about the interpretation of the `baseline` parameter for the clustering and visualization via `plot1GS`, i.e. which values are being displayed when choosing a baseline? And what's the influence of the other parameters of the clustering functions, including `group.vars` etc.? How does the interpretation differ between the two plots? And is it correct to interpret that lines that go down show a reduced expression in the treatment group ("FM") over the reference group?

```
# without baseline
TcGSA::plot1GS(expr = tcgsa_result$Estimations, 
               gmt = gmt_hallmark, 
               ref = "control",
               group_of_interest="FM",
               Subject_ID = si.df[colnames(norm.df),]$subject, 
               TimePoint = si.df[colnames(norm.df),]$day,
               clustering = TRUE, # only influences the coloring
               time_unit = "Day", 
               geneset.name = grep("GLYCOLYSIS", gmt_hallmark$geneset.names,value = TRUE),
               desc = FALSE)
```
![image](https://user-images.githubusercontent.com/4973546/56676114-95218500-668b-11e9-90dc-ece09719965c.png)

```
# With baseline Day 1
TcGSA::plot1GS(expr = tcgsa_result$Estimations, 
               gmt = gmt_hallmark, 
              baseline = 1, 
              ref = "control",
              group_of_interest="FM",
              Subject_ID = si.df[colnames(norm.df),]$subject, 
              TimePoint = si.df[colnames(norm.df),]$day,
              clustering = TRUE, # only influences the coloring
              time_unit = "Day", 
              geneset.name = gmt_hallmark$geneset.names[[1]],
              desc = FALSE)
```

![](https://raw.githubusercontent.com/friedue/Notes/master/images/tcgsa/baselineD1.png)

Another technical question: why can I not supply the pre-computed clustering results to `plot1GS` as I can for the generic `plot` command that generates the heatmap?

**Comment by borishejblum** [comment] 2019-04-24 19:08
Hi Friederike,

First thank you for your interest in our work, this is the perfect place to ask such questions.

When you set a baseline time-point in `plot1GS`, this means that what is being plotted at time t is the estimated value from TcGSA at time t minus the corresponding (for the same subject) estimated value at baseline. In my mind, this parameter is useful when you have a specific timepoint in your experiment that your want to use as a reference. 
If you don't specify `baseline`, then each gene is centered across all time points to have mean zero.

`group.var` is the argument that tells `plot1GS` that there are several groups, so in your case where you have 2 groups (namely 'FM' and 'controll'), you must specify it otherwise the median are computed across all samples regardless of the groups.

Concerning your technical question of specifying a pre-clustering of the gene, I updated the function and this should now be possible using the latest version of the package from GitHub.

Let me know if it does not work as expected or if you have further questions.

Best,
Boris

**Comment by friedue** [comment] 2019-04-24 19:10
Hi Boris, thanks for getting back to me so swiftly! I'll test the latest version.

In regard to the heatmap, I have trouble understanding how the color scheme in the heatmap corresponds to what I see in the single GS plot. Here's the heatmap using the baseline of day 1. I've marked the rows that correspond to the same gene set that was used for the plots above. Based on the single GS plots, I would have thought that the genes of cluster 3 of that gene set tend to go *down* over the time course, but the values in the heatmap suggest the opposite.

![](https://raw.githubusercontent.com/friedue/Notes/master/images/tcgsa/hm_baseline.png)

The code for the heatmap was as follows:

```
tcgsa_clust <- TcGSA::clustTrend(tcgs = tcgsa_result, 
                                 expr=tcgsa_result$Estimations,
                                 baseline = 1, # first time point,
                                 ref = "control",
                                 group_of_interest="FM")

plot(x = tcgsa_result,
     expr = tcgsa_result$Estimations,
     clust_trends = tcgsa_clust,
     legend.breaks = seq(from = -2,to = 2, by = 0.01),
     time_unit="D",
     subtitle="baseline: day 1",
     cex.label.row=1.5, cex.label.col=1, cex.main=0.7,
     heatmap.width = 0.1, dendrogram.size = 0.1, margins = c(5,15), heatKey.size = 0.5,
     descript = FALSE, # avoids printing of Description column to the row names
     color.vec = c("#D73027", "#FC8D59","seashell1", "#91BFDB", "#4575B4")
)
```

**Comment by friedue** [comment] 2019-04-24 19:14
Regarding the `group.var` option -- that's good to know, I didn't set it because in the user's guide example for the Pneumo/Flu example, it wasn't set either.

**Comment by borishejblum** [comment] 2019-04-25 12:41
Hi Friederike,

`baseline` and `group.var` cannot be used together (a baseline has no sense when you have a reference group).* I updated the package so that an error gets thrown in case the user attemps to use both in the same call.

Thank you very much for your comment, I realised their was a small mistake in the vignette regarding the "Pneumo vs saline" example, which should be using the `group.var` option. This will be corrected in the next release, meanwhile I attached the updated vignette here.

Do not hesitate if you have further questions.

Best,
Boris
[TcGSAtempvignette.zip](https://github.com/borishejblum/TcGSA/files/3116888/TcGSAtempvignette.zip)

**Comment by friedue** [comment] 2019-04-25 13:22
Hi Boris,

thanks for the clarification and the updates. Would you mind also addressing my confusion regarding the labeling/coloring of the heatmap and how those values relate to the 1GS-plots?

**Comment by borishejblum** [comment] 2019-04-25 13:51
I believe the discrepency you observed between the heatmap and the 1GS plot is due to the fact that each function uses its own clustering of the identified trends and some label-switching can happen (I should force the label ordering according to an arbitrary criteria so that it remains consistent accross different plots, I'll add it on my TODO list for TcGSA).

However, given your application seem to have several groups, those graphs are probably not what you want given they use a baseline instead of the reference group.

I hope that clarifies things, do not hesitate if you have further questions.

Best,
Boris

**Comment by friedue** [comment] 2019-04-25 14:09
Yes, baseline approach does not necessarily seem like the best choice for my data set, I guess, I could run the baseline analysis on either group separately.

You added the option `precluster` yesterday, but the expected input format is very different from what the heatmap-generating plot function accepts via `clust_trends`. Ideally, one would use the `cluster` function first and then supply the resulting object to both the heatmap and `plot1GS` functions. If you have an idea of how to retrieve the appropriate information from the cluster object for the current implementation in `plot1GS`, do let me know.

**Comment by borishejblum** [comment] 2019-04-25 15:01
You can access genesets partition from the results of a `clustTrend()` call through the following command:
```r
clust$GenesPartition$name_of_your_geneset
```

**Comment by friedue** [comment] 2019-04-25 15:21
Re-running clustTrend now gives me an error:

```
>tcgsa_clust <- clustTrend(tcgs = tcgsa_result, 
                                 expr=tcgsa_result$Estimations,
                                 Subject_ID = si.df[colnames(norm.df), "subject"],
                                 ref = "control",
                                 group_of_interest="DN", 
                                 group.var = si.df[colnames(norm.df), "group"],
                                 TimePoint = si.df[colnames(norm.df), "day"])
Error in svd(xs, nu = 0) : infinite or missing values in 'x'

> packageVersion("TcGSA")
[1] ‘0.12.3’
```
I got the same error for the earlier version (0.12.2), which is, I think, the main reason I stuck with the `baseline` option to begin with because it didn't throw an error (and according to the previous vignette it didn't seem inappropriate).

**Comment by borishejblum** [comment] 2019-04-25 16:16
It is difficult to diagnose where is the error coming from without a reproducible example.

This `svd(xs, nu = 0)` call is from the `cluster::clusGap()` function that compute the gap statistics (to estimate the best number of trends for each gene set). 

One thing you could try to do is to lower the `max_trends` argument to 3 or 2 and see if that helps ?

**Comment by friedue** [comment] 2019-04-25 18:52
With `max_trend == 1` it works, but I guess that's because it's turning off the clustering (2 or 3 still throw the same error)?
I could share the data with you in private if you wanted to have a look, but is there anything obvious to look out for?

**Comment by borishejblum** [comment] 2019-04-26 09:44
Hi Friederike,

Indeed, `max_trend =1` is not very useful and turns off the clustering. I do not see why this is happening. One thing you can look for is if you have any `NA`s in your data/estimations (but I'm doubtful this would be the cause)...

If you are OK to share your data with me, I will take a look and debug what is happening. Feel free to anonymize/shuffle everything (obviously), the only thing that I need is to be able to reproduce your error.

Boris

**Comment by friedue** [comment] 2019-04-26 14:01
Thanks for the kind offer! I'll use the academic email address I see on your blog to share a link to the files if that's ok.

**Comment by borishejblum** [comment] 2019-04-26 15:08
Yes, you can use my @u-bordeaux.fr email address.

**Comment by borishejblum** [comment] 2019-04-29 23:24
Hi Friederike,

Thank you for sending me data that reproduced your error.
Indeed, this visualisation failure had to do with `NA`s: it turns out you have an unbalanced design (one replicate is not observed at one of the time points), and `clust.trend()` was not very careful in the way it handled `NA`... This should be fixed in the latest commit (and those fixes are on their way to CRAN).

Hopefully this lets you use TcGSA smoothly now. Do not hesitate to reach out if you have further questions.

Best,
Boris

**Closed by borishejblum** 2019-04-29 23:24 UTC
Labels: bug, enhancement, help wanted, question

**Comment by friedue** [comment] 2019-04-30 01:57
Thanks for the swift help; indeed, the clustering now worked! Thanks a lot!

Is there a way to retrieve the leading edge gene for the gene sets that come up as significant? I.e., somehow identify those genes that are most strongly correlated with the phenotype over time?

**Comment by borishejblum** [comment] 2019-04-30 12:50
Hi Friederike,

Since TcGSA is not an enrichment method but directly models gene sets expression as a whole, it does not provide such hierarchy between genes.

Boris

**Comment by friedue** [comment] 2019-04-30 13:30
Ah, I see! Thanks!
